<?php

namespace AdminBundle\Repository;

/**
 * RecearchImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecearchImageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *
     * @return RecearchImage[]
     */
    public function findAllRecearchImage()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->from('AdminBundle:RecearchImage', 'r')
            ->select('r.id_recearch')
            ->innerJoin('', 'cp')

            ->getQuery()
            ->getResult();
    }
}
