<?php

namespace CoreBundle\Repository;

/**
 * ImageModerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageModerationRepository extends \Doctrine\ORM\EntityRepository
{
}
