<?php

namespace CoreBundle\Repository;

/**
 * TypePictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeImageRepository extends \Doctrine\ORM\EntityRepository
{
}
