<?php

namespace CoreBundle\Repository;

/**
 * Cat_testRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cat_testRepository extends \Doctrine\ORM\EntityRepository
{
}
