<?php

namespace CoreBundle\Repository;

/**
 * SuperImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuperImageRepository extends \Doctrine\ORM\EntityRepository
{
}
